---
title: "Class 9 Unsupervised Learning"
author: "Kiana Miyamoto"
date: "10/30/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
wisc.df<-read.csv("~/BGGN213_Bioinformatics/class09/WisconsinCancer.csv")
#head(wisc.df)
```

Here we examine data from `r nrow(wisc.df)` patient samples.

```{r}
table(wisc.df$diagnosis)
x<-table(wisc.df$diagnosis)
```

In this dataset we have `r x[1]` benign and `r x[2]` malignant.

```{r}
wisc.data<-as.matrix(wisc.df[,3:32])
```

> Q. How many variables/features in the data are suffixed with _mean?

```{r}
colnames(wisc.df)
grep("_mean", colnames(wisc.df), value=TRUE)
length(grep("_mean", colnames(wisc.df), value=TRUE))
```

```{r}
colMeans(wisc.data)
round(apply(wisc.data,2,sd), 3)
```

```{r}
wisc.pr <- prcomp(wisc.data, scale=TRUE )
summary(wisc.pr)
```

```{r}
biplot(wisc.pr)
```
Plot PC1 vs PC2 and color by M/B cancer/non-cancer diagnosis
```{r}
plot(wisc.pr$x[,1],wisc.pr$x[,2], col=wisc.df$diagnosis,xlab="PC1", ylab="PC2" )
```
Black=benign, Red=malignant

```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,3], col=wisc.df$diagnosis, xlab="PC1", ylab="PC3")
```

```{r}
x<-summary(wisc.pr)
x$importance[,"PC1"]
```
The first PC captures `r x$importance[2,"PC1"] *100 of the original variance in the dataset.

```{r}
which(x$importance[3,]>0.7)[1]
```


```{r}
data.scaled<- scale(wisc.data)
data.dist<- dist(data.scaled)
wisc.hclust<- hclust(data.dist)
```

```{r}
plot(wisc.hclust)
abline(h=19,col="red", lty=2)
```

```{r}
wisc.hclust.clusters<-cutree(wisc.hclust, k=4)
```

```{r}
table(wisc.hclust.clusters,wisc.df$diagnosis)
```

```{r}
wisc.km<-kmeans(wisc.data, centers=2, nstart=20)
```

```{r}
table(wisc.km$cluster, wisc.df$diagnosis)
```

```{r}
table(wisc.km$cluster, wisc.hclust.clusters)
```

```{r}
#Take the first 7PCs
wisc.pr.hclust<-hclust(dist(wisc.pr$x[,1:7]), method="ward.D2")
plot(wisc.pr.hclust)
```

```{r}
grps<-cutree(wisc.pr.hclust,k=2)
table(grps)
```

```{r}
table(grps, wisc.df$diagnosis)
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
```

```{r}
plot(wisc.pr$x[,1:2], col=wisc.df$diagnosis)
```

```{r}
#Reordering the factors
g<-as.factor(grps)
levels(g)
```
```{r}
g<-relevel(g,2)
levels(g)
```

```{r}
plot(wisc.pr$x[,1:2], col=g)
```

```{r}
## Use the distance along the first 7 PCs for clustering
wisc.pr.hclust<- hclust(dist(wisc.pr$x[,1:7]), method="ward.D2")
```

```{r}
wisc.pr.hclust.clusters<- cutree(wisc.pr.hclust,k=2)
table(wisc.pr.hclust.clusters, wisc.df$diagnosis)
```

```{r}
table(wisc.km$cluster, wisc.df$diagnosis)
table(wisc.hclust.clusters, wisc.df$diagnosis)
```

```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=g)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```

