---
title: "Class 7 R functions and packages"
author: "Kiana Miyamoto"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Revisit our functions from last day
```{r}
source("http://tinyurl.com/rescale-R")
```

## Let's try our rescale() function from last day
```{r}
rescale(1:10)
```
```{r}
rescale( c(3,10,NA,7,"barry"))
```

```{r}
rescale2(c(3,10,NA,"barry"))
```

is.numeric()

## Write a function both_na()
We want to write a function, called both_na(), that counts how many positions in two input vectors, x and y, both have a missing value
```{r}
# Should we start like this? No!
both_na <- function(x, y) {
 # something goes here? body
}
```

```{r}
## from StackOverflow
# Lets define an example x and y
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)
is.na(x)
is.na(y)
```


```{r}
which(is.na(x))
```

```{r}
both_na<-function(x,y){
  sum(is.na(x)&is.na(y))
}
both_na(x,y)
  
```
```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
y3<-c(1, NA, NA, NA, NA, NA)
both_na(x,y1)
## what will this return?
both_na(x,y2)
both_na(x,y3)
```

```{r}
plot(1:10,col="red")
plot(1:10,col=c("red","green","blue"))
```

```{r}
both_na2<- function(x,y) {
  if(length(x) != length(y)) {
    stop("Input x and y should be the same legnth")
  }
  sum(is.na(x) & is.na(y))
}
both_na2(x,y1)
both_na2(x,y2)
both_na2(x,y3)
```

```{r}
# student 1
s1 <-c(100, 100, 100, 100, 100, 100, 100, 90)
# student 2
s2<-c(100, NA, 90, 90, 90, 90, 97, 80)
# now grade all students in an example class
url <- "https://tinyurl.com/gradeinput"

s1r<-s1[-which.min(s1)]
mean(s1r)


s2[is.na(s2)]<-0

s2r<-s2[-which.min(s2)]
mean(s2r)

grade<- function(x) {
  x[is.na(x)]<-0
xr<-x[-which.min(x)]
mean(xr)
}
grade(s1)
grade(s2)
grade(url)
```

